In [23]:
import math
math.sqrt(25)
math.pi

3.141592653589793

In [24]:
import math as mt
mt.sqrt(25)

5.0

In [28]:
from numpy import random
import numpy as np

dataOne = random.rand(5,5)
print(dataOne)

np.mean(dataOne)

[[0.86486206 0.89403934 0.97920826 0.01419671 0.75305827]
 [0.75692505 0.8901554  0.12875052 0.94426628 0.32985905]
 [0.43280459 0.88666019 0.98726862 0.20479523 0.80522996]
 [0.29060588 0.07528781 0.32923869 0.52095047 0.10971786]
 [0.00470454 0.18999308 0.97119733 0.30841204 0.48170179]]


0.5261555614749451

In [29]:
varOne = 25

varTwo = 25.0

varThree = varOne + varTwo

print(varThree)

50.0


In [ ]:
varOne = 25
varTwo = 'Hello'
varThree = varOne + varTwo
print(varThree)
## This one throws an error

In [31]:
listOne = [1,2,3,4]
print(listOne[1:3])

[2, 3]


In [32]:
tel = {'jack': 4098, 'sape': 4139}

for key, value in tel.items() :
    print(key, value)

jack 4098
sape 4139


In [19]:
def returnSum(dict): 
     sum = 0
     for i in dict.values(): 
           sum = sum + i 
     return sum

def returnMinus(dict): 
     min = 0
     for i in dict.values(): 
           min = min - i 
     return min
  
dict = {'a': 1, 'b':2, 'c':3} 
print("Sum :", returnSum(dict)) 
print("Minus :", returnMinus(dict)) 

print(dict['a'] + dict['b'] * dict['c'])

Sum : 6
Minus : -6
7


In [20]:
import pandas as pd

df = pd.read_csv("default_of_credit_card_clients.csv") 

df.head(10)

Unnamed: 0         X1   X2         X3        X4   X5     X6     X7     X8  \
0         ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3   
1          1      20000    2          2         1   24      2      2     -1   
2          2     120000    2          2         2   26     -1      2      0   
3          3      90000    2          2         2   34      0      0      0   
4          4      50000    2          2         1   37      0      0      0   
5          5      50000    1          2         1   57     -1      0     -1   
6          6      50000    1          1         2   37      0      0      0   
7          7     500000    1          1         2   29      0      0      0   
8          8     100000    2          2         2   23      0     -1     -1   
9          9     140000    2          3         1   28      0      0      2   

      X9  ...        X15        X16        X17       X18       X19       X20  \
0  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3   
1     -1  ...          0          0          0         0       689         0   
2      0  ...       3272       3455       3261         0      1000      1000   
3      0  ...      14331      14948      15549      1518      1500      1000   
4      0  ...      28314      28959      29547      2000      2019      1200   
5      0  ...      20940      19146      19131      2000     36681     10000   
6      0  ...      19394      19619      20024      2500      1815       657   
7      0  ...     542653     483003     473944     55000     40000     38000   
8      0  ...        221       -159        567       380       601         0   
9      0  ...      12211      11793       3719      3329         0       432   

        X21       X22       X23                           Y  
0  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
1         0         0         0                           1  
2      1000         0      2000                           1  
3      1000      1000      5000                           0  
4      1100      1069      1000                           0  
5      9000       689       679                           0  
6      1000      1000       800                           0  
7     20239     13750     13770                           0  
8       581      1687      1542                           0  
9      1000      1000      1000                           0  

[10 rows x 25 columns]